---
abstract: 'Bullet-proof rsync wrapper'
author:
  - 'Dominik Schulz <dominik.schulz@gauner.org>'
build_requires:
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sys-Bprsync
requires:
  Carp: 0
  Config::Yak: 0
  Config::Yak::RequiredConfig: 0
  English: 0
  File::Blarf: 0
  Job::Manager: 0
  Job::Manager::Job: 0
  Job::Manager::Worker: 0
  Linux::Pidfile: 0
  Log::Tree: 0
  Log::Tree::RequiredLogger: 0
  Moose: 0
  MooseX::App::Cmd: 0
  MooseX::App::Cmd::Command: 0
  Sys::CmdMod: 0
  Sys::Run: 0
  Try::Tiny: 0
  feature: 0
  mro: 0
  namespace::autoclean: 0
  perl: 5.010_000
resources:
  bugtracker: https://github.com/gittex/Sys-Bprsync/issues
  repository: git://github.com/gittex/Sys-Bprsync.git
version: 0.17
x_authority: cpan:TEX
